### ISSUE TITLE
Run occ command in background

### ISSUE THREAD

**Issue by kinglouie** [linuxserver/docker-nextcloud#187] opened 2021-02-25 12:52 UTC
I want to use the Nextcloud inotify watcher from [here](https://github.com/icewind1991/files_inotify/blob/master/README.md) and for this to work I need to run `occ files_external:notify -v 1` in the background but I don't know how to spawn a background process in this image. 
The official nextcloud docker image has supervisord integrated but I found nothing similiar in this image.
I would appreciate any hint how to achieve this :)

**Comment by aptalca** [comment] 2021-02-25 13:00
Cron or https://blog.linuxserver.io/2019/09/14/customizing-our-containers/

Closing because not a bug

**Closed by aptalca** 2021-02-25 13:00 UTC
