### ISSUE TITLE
[BUG] logging view is not working in Nextcloud 28.0.0 image

### ISSUE THREAD

**Issue by Elbullazul** [linuxserver/docker-nextcloud#390] opened 2023-12-17 14:49 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Navigating to `/settings/admin/logging` results in an empty page and new errors in the `/settings/admin/overview`

### Expected Behavior

The webpage should show logs as expected

### Steps To Reproduce

Open the 'logging' page in the admin sidebar or navigate to `/settings/admin/logging`

### Environment

```markdown
- OS: Debian 12
- How docker service was installed: official Docker
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.3"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIMEZONE}
    volumes:
      - ${BINDS}/nextcloud/config:/config
      - ${BINDS}/nextcloud/data:/data
    depends_on:
      - nextcloud-db
    restart: unless-stopped
    networks:
      - backend
      - shn_nextcloud
    labels:
      com.centurylinklabs.watchtower.enabled: true
      com.centurylinklabs.watchtower.depends-on: "/nextcloud-db"

  nextcloud-db:
    image: postgres:15 #latest
    container_name: nextcloud-db
    volumes:
      - ${BINDS}/nextcloud/pgdb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend
      - shn_backends
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  backend:
  shn_backends:
    external: true
  shn_nextcloud:
    external: true
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

using keys found in /config/keys
Initializing nextcloud 28.0.0.11 (this can take a while) ...
Upgrading nextcloud from 27.1.4.1 ...
Setting permissions
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: files_rightclick
Updating <lookup_server_connector> ...
Updated <lookup_server_connector> to 1.16.0
Updating <oauth2> ...
Updated <oauth2> to 1.16.3
Updating <password_policy> ...
Updated <password_policy> to 1.18.0
Updating <user_ldap> ...
Updated <user_ldap> to 1.19.0
Updating <files> ...
Updated <files> to 2.0.0
Updating <activity> ...
Updated <activity> to 2.20.0
Updating <circles> ...
Updated <circles> to 28.0.0-dev
Updating <cloud_federation_api> ...
Updated <cloud_federation_api> to 1.11.0
Updating <dav> ...
Fix broken values of calendar objects

 Starting ...

Clean up old calendar subscriptions from deleted users that were not cleaned-up


    0/0 [>---------------------------]   0% Starting ...
Updated <dav> to 1.29.1
Updating <files_sharing> ...
Updated <files_sharing> to 1.20.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.18.0
Updating <files_versions> ...
Updated <files_versions> to 1.21.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.18.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.10.0
Updating <comments> ...
Updated <comments> to 1.18.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.17.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.17.0
Updating <notifications> ...
Updated <notifications> to 2.16.0
Updating <systemtags> ...
Updated <systemtags> to 1.18.0
Updating <theming> ...
Migrate old user accessibility config

    0/0 [->--------------------------]   0% Starting ...
    0/0 [--->------------------------]   0%
 Starting ...

Updated <theming> to 2.3.0
Updating <dashboard> ...
Updated <dashboard> to 7.8.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.18.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.9.0
Updating <files_reminders> ...
Updated <files_reminders> to 1.1.0
Updating <logreader> ...
Updated <logreader> to 2.13.0
Updating <privacy> ...
Updated <privacy> to 1.12.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.18.0
Updating <recommendations> ...
Updated <recommendations> to 2.0.0
Updating <related_resources> ...
Updated <related_resources> to 1.3.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.18.0
Updating <settings> ...
Updated <settings> to 1.10.0
Updating <support> ...
Updated <support> to 1.11.0
Updating <survey_client> ...
Updated <survey_client> to 1.16.0
Updating <text> ...
Updated <text> to 3.9.1
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.17.0
Updating <twofactor_totp> ...
Updated <twofactor_totp> to 10.0.0-beta.2
Updating <updatenotification> ...
Updated <updatenotification> to 1.18.0
Updating <user_status> ...
Updated <user_status> to 1.8.1
Updating <viewer> ...
Updated <viewer> to 2.2.0
Updating <weather_status> ...
Updated <weather_status> to 1.8.0
Update app notes from App Store
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Initializing finished
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by thespad** [comment] 2023-12-17 14:59
Duplicate of https://github.com/linuxserver/docker-nextcloud/issues/387

**Closed by thespad** 2023-12-17 14:59 UTC
