### ISSUE TITLE
[FEAT] Add release tag for major versions

### ISSUE THREAD

**Issue by techsolo12** [linuxserver/docker-nextcloud#408] opened 2024-01-07 13:30 UTC
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I would suggest that we add a release tag that enables a major version such as 27, 28 and so on in the docker hub.

### Reason for change

With this change it is possible to stay on a major release when watchtower automatically updates the base images. It will always use only the latest version of a major release.
The reason for this is that the first versions of a major update on the nextcloud upstream usually have minor bugs. This means that the first releases can be waited for before the docker-compose is manually extended to the "new" major release.

### Proposed code change

Unfortunately, I find programming very difficult and it's not my thing at all. I am already proud when I finish my shell scripts. Unfortunately I can't actively contribute to this change and have to rely on the help of the community.

**Comment by j0nnymoe** [comment] 2024-01-07 13:32
Dupe of this: https://github.com/linuxserver/docker-nextcloud/issues/361 Where it's already been discussed.

**Closed by j0nnymoe** 2024-01-07 13:32 UTC
Labels: enhancement

**Comment by j0nnymoe** [comment] 2024-01-07 13:36
And to note about your watchtower comment, We do not [support nor recommend](https://docs.linuxserver.io/misc/support-policy/) any automatic updating tools for our containers. While yes you can get away with using them for some containers, Nextcloud is not one of those you can.
