### ISSUE TITLE
This version of Nextcloud is not compatible with PHP 8.0

### ISSUE THREAD

**Issue by MatzeK712** [linuxserver/docker-nextcloud#290] opened 2023-03-01 23:28 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

### Expected Behavior

Hi everyone, I have almost no experience with Docker. Is this due to the Docker or the UNRAID server? If it's on Docker, how can I change the PHP version? Or what exactly is the problem? Is an old Docker image from Nextcloud used here?   Thank you in advance for your help.

### Steps To Reproduce

After Docker-Update I get this Message

### Environment

```markdown
- OS: UNRAID
```

### CPU architecture

x86-64

### Docker creation

```bash
Docker updatet in UNRAID GUI
```

### Container logs

```bash
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

using keys found in /config/keys
**** The following site-confs have extensions other than .conf ****
**** This may be due to user customization. ****
**** You should review the files and rename them to use the .conf extension or remove them. ****
**** nginx.conf will only include site-confs with the .conf extension. ****
/config/nginx/site-confs/default.conf.bak
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment] 2023-03-01 23:32
Dupe of pinned message https://github.com/linuxserver/docker-nextcloud/issues/288

**Closed by j0nnymoe** 2023-03-01 23:32 UTC

**Comment by MatzeK712** [comment] 2023-03-01 23:45
Hello @j0nnymoe,
Thank you, I've already found that. But how can I load an old Docker image into Unraid?

**Comment by j0nnymoe** [comment] 2023-03-01 23:50
> Hello @j0nnymoe, Thank you, I've already found that. But how can I load an old Docker image into Unraid?

You edit the template and put the image stated in that issue in the image field. If you need more help, please do what the issue says and join our discord.
