### ISSUE TITLE
[BUG] Image contains PHP version too high for Nextcloud version

### ISSUE THREAD

**Issue by Aesir** [linuxserver/docker-nextcloud#289] opened 2023-02-25 20:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I updated to the current latest container (lscr.io/linuxserver/nextcloud:latest) yesterday and now Nextcloud is throwing this error.

> This version of Nextcloud is not compatible with > PHP 8.0.
> You are currently running 8.1.16.

### Expected Behavior

From a search, it looks like something that can be fixed by opening a command line into the container and modifying versions used but ideally the container would just work.

### Steps To Reproduce

1. In Unraid
2. Install/Update to `lscr.io/linuxserver/nextcloud:latest` as of Feb 24, 2023
3. Try to open Nextcloud homepage

### Environment

```markdown
- OS: Unraid Version: 6.11.5 
- How docker service was installed: Community Applications Plugin
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='nextcloud'
  --net='proxynet'
  --privileged=true
  -e TZ="America/Los_Angeles"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="*********"
  -e HOST_CONTAINERNAME="nextcloud"
  -e 'DOCKER_MODS'='linuxserver/mods:universal-package-install'
  -e 'INSTALL_PACKAGES'='clamav|clamav-daemon'
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='https://******************'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-logo.png'
  -p '4443:443/tcp'
  -v '/mnt/user/appdata/nextcloud_data/':'/data':'rw'
  -v '/mnt/user/appdata/nextcloud':'/config':'rw' 'lscr.io/linuxserver/nextcloud:latest'
```

### Container logs

```bash
[mod-init] Attempting to run Docker Modification Logic
[mod-init] Applying linuxserver/mods:universal-package-install files to container
[mod-init] linuxserver/mods:universal-package-install applied to container
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

using keys found in /config/keys
**** Adding clamav to OS package install list ****
**** Adding clamav-daemon to OS package install list ****
[mod-init] **** Installing all mod packages ****
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
(1/9) Installing json-c (0.16-r2)
(2/9) Installing libmspack (0.10.1_alpha-r0)
(3/9) Installing clamav-libs (0.105.2-r0)
(4/9) Installing freshclam (0.105.2-r0)
Executing freshclam-0.105.2-r0.pre-install
(5/9) Installing clamav-scanner (0.105.2-r0)
(6/9) Installing clamav-clamdscan (0.105.2-r0)
(7/9) Installing clamav-daemon (0.105.2-r0)
Executing clamav-daemon-0.105.2-r0.pre-install
(8/9) Installing musl-fts (1.2.7-r3)
(9/9) Installing clamav (0.105.2-r0)
Executing busybox-1.35.0-r29.trigger
OK: 375 MiB in 249 packages
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by Roxedus** [comment] 2023-02-25 20:24
Duplicate of https://github.com/linuxserver/docker-nextcloud/issues/288

**Closed by Roxedus** 2023-02-25 20:24 UTC

**Comment by Aesir** [comment] 2023-02-25 20:30
Maybe you guys shouldn't close issues until the fix is actually released? Mark it as pending the next release or something? It is still an open bug in the currently released version and it's standard to not look through closed bug history when making reports.

**Comment by nemchik** [comment] 2023-02-25 20:32
It is released. Please read #288 

There are specific instructions to upgrade nextcloud.

**Comment by Roxedus** [comment] 2023-02-25 20:43
> it's standard to not look through closed bug history when making reports.

But you did claim to have done so. 
![image](https://user-images.githubusercontent.com/7110194/221378776-1658f89f-b9d8-49cd-ade7-4e0f425d95b3.png)

**Comment by Aesir** [comment] 2023-02-25 21:17
> > it's standard to not look through closed bug history when making reports.
> 
> But you did claim to have done so. ![image](https://user-images.githubusercontent.com/7110194/221378776-1658f89f-b9d8-49cd-ade7-4e0f425d95b3.png)

Existing issues are open issues, that's my entire point.

**Comment by aptalca** [comment] 2023-02-25 21:45
I don't think you even looked at the issue we keep linking for you. There is nothing for us to fix or update. You are having this issue because you failed to read the readme. We are not going to keep an issue open until _you_ read and follow the readme, which would be pretty ridiculous, don't you think?

As far as we are concerned, this issue is entirely pebcak so it is considered `resolved`.

**Comment by nemchik** [comment] 2023-02-25 21:46
It's pinned. You can't even click the `New Issue` button without seeing it (and it's larger than the new issue button).
Desktop:
![image](https://user-images.githubusercontent.com/725456/221380642-96e0c387-aeb0-46ad-9b3b-47b45fc1e356.png)
Mobile:
![image](https://user-images.githubusercontent.com/725456/221380651-ab73eace-0269-485a-bfb3-55219c1d793a.png)

Our readme also includes information on this topic:
https://github.com/linuxserver/docker-nextcloud#application-setup
![image](https://user-images.githubusercontent.com/725456/221380703-8bed6d55-740c-4f7a-af0b-ad25ea660122.png)

And our changelog calls out new versions of PHP:
https://github.com/linuxserver/docker-nextcloud#versions
![image](https://user-images.githubusercontent.com/725456/221380744-6456ec85-8e97-42df-842e-af883be74524.png)

And our releases note the most recent change from our changelog:
https://github.com/linuxserver/docker-nextcloud/releases
https://github.com/linuxserver/docker-nextcloud/releases/tag/25.0.4-ls224
https://github.com/linuxserver/docker-nextcloud/releases/tag/25.0.3-ls223
![image](https://user-images.githubusercontent.com/725456/221380812-7731c3b3-9c16-4841-b1b0-ba14696180d2.png)
https://github.com/linuxserver/docker-nextcloud/releases/tag/25.0.3-ls222
https://github.com/linuxserver/docker-nextcloud/releases/tag/25.0.3-ls221
![image](https://user-images.githubusercontent.com/725456/221380826-dc071825-516a-44aa-af4d-28478e230c66.png)
(there's more, but I think the point should be pretty clear)


And yes, the other issues are closed, because the issues are resolved by following the instructions in #288 
Either way, searching for closed issues (not just open issues) is a good way to see if someone else has already had the same problem and found a resolution.
https://github.com/linuxserver/docker-nextcloud/issues?q=is%3Aissue+This+version+of+Nextcloud+is+not+compatible+with+%3E+PHP
There are multiple issues, dating back years, that are all solved the same way. #288 is fairly new and serves as an easy way for our team to reference where the instructions are (aside from also being in the readme).

---

If you have a suggestion for how we could better communicate this information I am happy to hear it.

**Comment by Aesir** [comment] 2023-02-26 02:52
> It's pinned. You can't even click the New Issue button without seeing it (and it's larger than the new issue button).

The Unraid support link goes directly to creating a New Issue. I used the New Issue page to open Issues (which defaults to Open issues and doesn't show the pinned Closed issue) in a new tab and then did a Duck Duck Go search for the error which found nothing from LSIO but did have some mitigation steps for people working with a standard install. I've had this installed for more than a year so I haven't seen any changes to your ReadMe.

The in-app updater rarely works, it usually fails by timing out (CLI updater seems to be working right now), so I tend to just wait for you guys to update the image since I don't have my install publicly accessible outside of my VPN. 

> If you have a suggestion for how we could better communicate this information I am happy to hear it.

Best option I can think of is to create an FAQ as one of Github's project wiki pages and have the Unraid container's support link go to that rather than directly to creating a new issue. Closed issues are really bad for documentation of anything since the entire point of the tag is to hide stuff that is no longer an active concern while maintaining it for historical reference. 

I don't know if it's feasible but surfacing a message in the docker logs like you do with updated configs would also be a good option since that's the first place anyone is likely to check when something goes wrong with a container.

**Comment by nemchik** [comment] 2023-02-26 03:33
> it's standard to not look through closed bug history when making reports

You implied that you searched open issues.

> did a Duck Duck Go search for the error which found nothing from LSIO

DDG is not the source of truth for issues in a github repository. It would be the issues tab, which is visible when creating an issue.

> Closed issues are really bad for documentation

That's why it's pinned. It's visible at the top of the open issues page in a way that calls attention.

> I haven't seen any changes to your ReadMe

The change log is visible in our readme, as well as the application setup instructions with the information about updating nextcloud (screenshots posted in my last reply).

> surfacing a message in the docker logs like you do with updated configs

I will look into this. If it's possible, I'll add it.

**Comment by Aesir** [comment] 2023-02-26 07:12
> You implied that you searched open issues.

I did. I've been banging my head against the wall trying to figure out why you guys think I would have seen a closed issue at all when you have to explicitly remove the search term to see them. After the 10th-12th time opening the page I finally figured out what the issue was. I always automatically scroll down to hide the excessive header on Github and show only the content. 
![image](https://user-images.githubusercontent.com/447759/221396960-c9b45309-2d90-4684-ae63-6589ea6435ea.png)

I literally never saw the box and didn't see the pinned issue unless I searched all issues
![image](https://user-images.githubusercontent.com/447759/221397064-caa963e3-b858-410b-9de1-62dec1612b14.png)
in which case it shows up in the list of issues. 

Not really something you guys can do anything about I don't think (definitely move it under the search bar if you can and you'll see the duplicate issues go away completely), it's just one of the bad parts of Github's UI/UX. Stuff adjacent to the giant headers get lost in the headers and people are trained to see the search bar as the top of the actual page, so anything above the search bar is automatically written off as part of the header without being registered by the user unless they're specifcally looking for it. Similar issue to apps that open modal dialogues for both success and failure, people don't even register them after a little while and just click through without looking or noticing that the box is different. But yeah, I wouldn't expect the vast majority of your users to notice the box is even there.

**Comment by nemchik** [comment] 2023-02-26 13:34
What I'm hearing is: you choose to scroll so the pinned issue that shows above opened or closed issues was not in view.

That's not something we can fix. You can argue in until you're blue in the face that the choices you made (not reading the readme, changelog, release notes, searching closed issues, scrolling past pinned issues)  are all everybody else's fault (your even blaming github in your last comment...).

As I mentioned above, I'll see if there's anything I can do to put a version check or compatibility notice inside the container logs, similar to the outdated confs messaging.

**Comment by nemchik** [comment] 2023-06-26 13:33
> I updated the repository link wrongly and now i cant even see nextcloud in unraid app list. Under Previous Apps page , it says "REMOVE ONLY"
> 
> I cant access the nextcloud in anyway , kindly help.

Please open a new issue and fill out the information in the issue template.
