### ISSUE TITLE
[BUG] Incompatible PHP version

### ISSUE THREAD

**Issue by ptheofan** [linuxserver/docker-nextcloud#287] opened 2023-02-24 11:42 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After pulling the latest image I get the following error.
```
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.
```

### Expected Behavior

Nextcloud to be working as usual.

### Steps To Reproduce

Version Pulled
linuxserver/nextcloud:latest
DIGEST:sha256:0e8a61a9dd255b576ff4d72aeb62bd6b913954f1b9925cff895d2abf09bdb3d0

### Environment

```markdown
- OS:Unraid
```

### CPU architecture

x86-64

### Docker creation

```bash
Your container
linuxserver/nextcloud:latest
DIGEST:sha256:0e8a61a9dd255b576ff4d72aeb62bd6b913954f1b9925cff895d2abf09bdb3d0
```

### Container logs

```bash
Kinda irrelevant but here it is


[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    99
User gid:    100
-------------------------------------

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-10-24 │ 2022-08-16 │ /config/nginx/nginx.conf                                               │
│            │ 2022-08-20 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```
```

**Comment by thespad** [comment] 2023-02-24 11:43
Duplicate of https://github.com/linuxserver/docker-nextcloud/issues/285

**Closed by thespad** 2023-02-24 11:43 UTC
