### ISSUE TITLE
NextCloud not compatible and unreachable

### ISSUE THREAD

**Issue by egobuster1** [linuxserver/docker-nextcloud#296] opened 2023-03-07 19:26 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am unable to access nextcloud locally or through proxy after recent upodate. 

```
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.
```

### Steps To Reproduce

access local URL

### Environment

```markdown
- OS:Unraid
- How docker service was installed: App Store
```

### CPU architecture

x86-64

### Docker creation

```bash
App store on unraid
```

### Container logs

```bash
text  error  warn  system  array  login  

│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2022-08-16 │ /config/nginx/nginx.conf                                               │
│            │ 2022-08-20 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2022-08-16 │ /config/nginx/nginx.conf                                               │
│            │ 2022-08-20 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
This version of Nextcloud is not compatible with > PHP 8.0.<br/>You are currently running 8.1.16.[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║      
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

using keys found in /config/keys
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2021-06-15 │ 2022-08-16 │ /config/nginx/nginx.conf                                               │
│            │ 2022-08-20 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by MuQ-dev** [comment] 2023-03-08 11:46
This is a duplicate of #288. Please follow the steps there.

**Comment by MuQ-dev** [comment] 2023-03-08 11:47
In short: You not only have to update the docker container regularly, but also the nextcloud version in the container. You haven't been updating nextcloud, so it can't use php 8.1.

**Closed** 2023-03-08 14:09 UTC
