### ISSUE TITLE
[BUG] HTTP Headers not set with Linuxserver.io version:- 27.0.1-ls262 Build-date:- 2023-08-08T11:50:58+00:00

### ISSUE THREAD

**Issue by tincanfury** [linuxserver/docker-nextcloud#348] opened 2023-08-10 18:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The "X-Robots-Tag" HTTP header is not set to "noindex, nofollow". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips ↗

### Steps To Reproduce

performed a docker-compose update to,
Linuxserver.io version:- 27.0.1-ls262 Build-date:- 2023-08-08T11:50:58+00:00

### Environment

```markdown
OS: OMV 6.5.7
docker service was installed via distro's packagemanager
```

### CPU architecture

x86-64

### Docker creation

```bash
$ docker-compose pull nextcloud
[+] Pulling 8/10
[+] Pulling 10/10yers [⣿⣿⣿⣿⣿⣿⣿⡀⣿] 64.06MB/273.9MB Pulling                                                        234.8s
 ✔ nextcloud 9 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                         458.6s
   ✔ 288f10deefc5 Pull complete                                                                                    4.6s
   ✔ 8bc286c87514 Pull complete                                                                                    4.6s
   ✔ fc17cd253e4c Pull complete                                                                                    4.7s
   ✔ fe000ddf37eb Pull complete                                                                                   14.1s
   ✔ 4801a1684981 Pull complete                                                                                   14.6s
   ✔ 422e43ed2adb Pull complete                                                                                   30.1s
   ✔ db9a099c1150 Pull complete                                                                                   30.5s
   ✔ cd10ad655eb6 Pull complete                                                                                  455.1s
   ✔ e62121bbe6bc Pull complete                                                                                  455.2s
root@home [~/docker]$
root@home [~/docker]$ docker-compose up -d nextcloud
[+] Running 2/2
 ✔ Container nextclouddb  Started                                                                                 13.3s
 ✔ Container nextcloud    Started
```

### Container logs

```bash
Clean up old calendar subscriptions from deleted users that were not cleaned-up
    0/0 [>---------------------------]   0% Starting ...
Updated <dav> to 1.27.0
Updating <files_external> ...
Updated <files_external> to 1.19.0
Updating <files_sharing> ...
Updated <files_sharing> to 1.19.0
Updating <files_trashbin> ...
Updated <files_trashbin> to 1.17.0
Updating <files_versions> ...
Updated <files_versions> to 1.20.0
Updating <sharebymail> ...
Updated <sharebymail> to 1.17.0
Updating <workflowengine> ...
Updated <workflowengine> to 2.9.0
Updating <comments> ...
Updated <comments> to 1.17.0
Updating <firstrunwizard> ...
Updated <firstrunwizard> to 2.16.0
Updating <nextcloud_announcements> ...
Updated <nextcloud_announcements> to 1.16.0
Updating <notifications> ...
Updated <notifications> to 2.15.0
Updating <theming> ...
Migrate old user accessibility config
    0/0 [->--------------------------]   0% Starting ...
Updated <theming> to 2.2.0
Updating <bruteforcesettings> ...
Updated <bruteforcesettings> to 2.7.0
Updating <contactsinteraction> ...
Updated <contactsinteraction> to 1.8.0
Updating <dashboard> ...
Updated <dashboard> to 7.7.0
Updating <federatedfilesharing> ...
Updated <federatedfilesharing> to 1.17.0
Updating <files_pdfviewer> ...
Updated <files_pdfviewer> to 2.8.0
Updating <files_rightclick> ...
Updated <files_rightclick> to 1.6.0
Updating <logreader> ...
Updated <logreader> to 2.12.0
Updating <privacy> ...
Updated <privacy> to 1.11.0
Updating <provisioning_api> ...
Updated <provisioning_api> to 1.17.0
Updating <recommendations> ...
Updated <recommendations> to 1.6.0
Updating <related_resources> ...
Updated <related_resources> to 1.2.0
Updating <serverinfo> ...
Updated <serverinfo> to 1.17.0
Updating <settings> ...
Updated <settings> to 1.9.0
Updating <support> ...
Updated <support> to 1.10.0
Updating <survey_client> ...
Updated <survey_client> to 1.15.0
Updating <text> ...
Updated <text> to 3.8.0
Updating <twofactor_backupcodes> ...
Updated <twofactor_backupcodes> to 1.16.0
Updating <twofactor_totp> ...
Updated <twofactor_totp> to 9.0.0
Updating <updatenotification> ...
Updated <updatenotification> to 1.17.0
Updating <user_status> ...
Updated <user_status> to 1.7.0
Updating <viewer> ...
Updated <viewer> to 2.1.0
Updating <weather_status> ...
Updated <weather_status> to 1.7.0
Update app notes from App Store
Update app recognize from App Store
Update app camerarawpreviews from App Store
Update app maps from App Store
Update app memories from App Store
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Initializing finished
System config value memcache.locking set to string \OC\Memcache\APCu
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2022-08-20 │ 2023-06-23 │ /config/nginx/site-confs/default.conf                                  │
│ 2022-08-16 │ 2023-04-13 │ /config/nginx/nginx.conf                                               │
│ 2022-08-20 │ 2023-06-24 │ /config/nginx/ssl.conf                                                 │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by aptalca** [comment] 2023-08-10 19:04
The answer is in the log
`The following active confs have different version dates than the samples that are shipped.`

**Comment by tincanfury** [comment] 2023-08-10 20:11
OK, but why, if the new docker image is supposed to include all the necessary files, is this issue appearing after that change? Shouldn't the shipped version not have this issue?

**Comment by tincanfury** [comment] 2023-08-10 20:29
copying the provided "sample" versions to the active version, restarting the container, and I still get,
_The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.
The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips_

I'm noticing the site-confs/default.conf does have X-Frame-Options set correctly, so unsure about what's going on there.
Strict-Transport-Security is in none of those three files.

**Comment by aptalca** [comment] 2023-08-10 20:32
We don't overwrite user configurable files. We inform the user and let them make that decision

**Comment by tincanfury** [comment] 2023-08-14 15:26
how does the system check? because I don't believe I ever edited those files from however they were provided in previous containers. When I did a diff between my original and the sample version from the new container the only differences found were the file version information and the lines that of the changes that "needed" to be made.

**Comment by nemchik** [comment] 2023-08-14 19:35
> how does the system check? because I don't believe I ever edited those files from however they were provided in previous containers. When I did a diff between my original and the sample version from the new container the only differences found were the file version information and the lines that of the changes that "needed" to be made.

The way the check works is by comparing the date in the top of the active config to the date in the top of the corresponding sample.

Even if you never changed the file, if we updated the sample your active conf would be out of date. As mentioned, we do not overwrite active user confs, so in this situation we log a message letting you know you need to compare the new sample to your currently active conf.

Some users choose to customize their active confs, so we cannot automatically update confs for all users because we would have to overwrite customizations.

**Comment by tincanfury** [comment] 2023-08-14 19:53
OK, so if I'm understanding correctly, essentially the user will ALWAYS need to check those files compared to the latest sample to see if they need to make any modifications?

**Comment by aptalca** [comment] 2023-08-14 21:38
Not always. The logs tell you when you need to

**Comment by drizuid** [comment] 2023-09-11 12:25
Problem is due to outdated confs the user did not update. Sufficient information regarding this has been providing, closing issue as non reproducible.

**Closed by drizuid** 2023-09-11 12:25 UTC
