### ISSUE TITLE
[BUG] default site-conf is broken

### ISSUE THREAD

**Issue by Gamer92000** [linuxserver/docker-nextcloud#403] opened 2024-01-02 04:40 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The changes to the default site conf introduced in 35de5f814cec310d92e6a47ff6fea66125ebfb06 prohibit some files from loading properly. Notably, `/js/core/merged-template-prepend.js` never loaded for me, resulting in a 404.

### Expected Behavior

Files like `/js/core/merged-template-prepend.js` properly load.

### Steps To Reproduce

1. Setup the container
2. Go to `/js/core/merged-template-prepend.js`.
3. Get a `404`

### Environment

```markdown
- OS: Ubuntu 22.04.3 LTS x86_64
- How docker service was installed: from the official Docker repos, version `5:24.0.7-1~ubuntu.22.04~jammy`
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3"

services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - TZ=Europe/Berlin
    volumes:
      - /jbod/nextcloud/config:/config
      - /jbod/nextcloud/data:/data
    restart: unless-stopped
    labels:
      traefik.enable: true
      [...]
    networks:
      - traefik
      - default
```

### Container logs

```bash
[migrations] started
[migrations] 01-nginx-site-confs-default: skipped
[migrations] 02-default-location: skipped
[migrations] done
usermod: no changes
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────

using keys found in /config/keys
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

### Nginx error log
```plain
2024/01/02 05:23:02 [error] 370#370: *1 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory), client: <redacted>, server: _, request: "GET /js/core/merged-template-prepend.js HTTP/2.0", host: <redacted>
```

**Comment by ownedge13** [comment] 2024-01-02 12:45
i have the same issue when i go in the shell of the docker the merged-template-prepend.json is in /app/www/public/core/js
but it search it in
2024/01/02 13:21:57 [error] 420#420: *16 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory)



iirc i'm stuck with that error starting the 25 december

**Comment by thehoodbuddha** [comment] 2024-01-02 15:33
I am having the same issue here after upgrading to the new `default.conf`:

Error logs in the nginx logs:

```
2024/01/02 15:23:57 [error] 412#412: *245 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory), client: 192.168.178.21, server: _, request: "GET /js/core/merged-template-prepend.js?v=c5940ea3-19 HTTP/1.1", host: "removed"
```

**Comment by drizuid** [comment] 2024-01-02 16:06
we have a PR being confirmed now to resolve this. applies to https://github.com/linuxserver/docker-nextcloud/issues/402 also

**Comment by ownedge13** [comment] 2024-01-03 13:02
i'm sorry to bother or maybe it's something else but with the new default.conf i still got the error
2024/01/03 13:53:51 [error] 392#392: *2448 open() "/app/www/public/js/core/merged-template-prepend.js" failed (2: No such file or directory)

and with the old default.conf (i use the 2023/06/23 one) it work

if you look the error it search /app/www/public/js/core/merged-template-prepend.js

but in the docker the file is in /app/www/public/core/js/merged-template-prepend.js

**Comment by drizuid** [comment] 2024-01-03 16:22
you guys are correct, its not fixed, im working on a new PR now. sorry!

**Comment by drizuid** [comment] 2024-01-03 18:00
mr pr is here, but isn't covering all the issues yet. you're still welcome to play with it. https://github.com/linuxserver/docker-nextcloud/pull/405

**Comment by drizuid** [comment] 2024-01-03 19:02
hi guys, please test and report back 
`lspipepr/nextcloud:amd64-28.0.1-pkg-1497da69-dev-4030be827853102c904c898015197f9583a2f5fb-pr-405`

**Comment by drizuid** [comment] 2024-01-03 20:11
to avoid this affecting more and more people, since we have consensus from an affected user in this ghi (own) and from the other thread related to the same issue, ill consider this resolved

**Closed** 2024-01-03 23:43 UTC
Labels: work-in-progress
