### ISSUE TITLE
[BUG] onlyoffice refuses to connect

### ISSUE THREAD

**Issue by gacpac** [linuxserver/docker-nextcloud#447] opened 2024-06-26 04:58 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when accessing or opening a document i get an error message for connection refused to https://documentserver.mydomain.com. 

However if I try manually using the local IP from the onlyofficedocker and also disable certificate verification to force it connect. Trying the same process opening a document it works. It's quite strange unless something has been updated that I must update somewhere

### Expected Behavior

The expected behavior should be the current normal operation opening a file and by using https://documentserver.mydomain.com at the settings the file should open without giving me a refused connection. 

### Steps To Reproduce

Simply try to open a file and make sure the docker for onlyoffice is working and is already going through the reverse proxy 

### Environment

```markdown
- OS:Unraid 6.12.10
- How docker service was installed: communityapps, has been running for ages no issues.
```

### CPU architecture

x86-64

### Docker creation

```bash
docker run
  -d
  --name='OnlyOfficeDocumentServer'
  --net='proxynet'
  -e TZ="America/New_York"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="OnlyOfficeDocumentServer"
  -e 'JWT_ENABLED'='true'
  -e 'JWT_SECRET'='jwtsupersecretpassword'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:4430]'
  -l net.unraid.docker.icon='https://github.com/chvb/docker-templates/raw/master/chvb/img/OnlyOfficeDocumentServer.jpg'
  -p '8084:80/tcp'
  -p '4430:443/tcp'
  -v '/mnt/user/appdata/onlyofficeds/logs':'/var/log/onlyoffice':'rw'
  -v '/mnt/user/appdata/onlyofficeds/Data':'/var/www/onlyoffice/Data':'rw'
  -v '/mnt/user/appdata/onlyofficeds/lib':'/var/lib/onlyoffice':'rw'
  -v '/mnt/user/appdata/onlyofficeds/database':'/var/lib/postgresql':'rw'
  -v '/mnt/user/appdata/onlyofficeds/fonts':'/usr/share/fonts/':'rw' 'onlyoffice/documentserver:latest'
d61f410c985ce7d5f7301c658a80be9956ed57da63701750469f1ec7fe39dad5
```

### Container logs

```bash
───────────────────────────────────────
Linuxserver.io version: 29.0.3-ls327
Build-date: 2024-06-25T14:59:40+00:00
───────────────────────────────────────
    
using keys found in /config/keys
Initializing nextcloud 29.0.3.4 (this can take a while) ...
Upgrading nextcloud from 29.0.2.2 ...
Setting permissions
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <text> ...
Updated <text> to 3.10.1
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Initializing finished
**** The following active confs have different version dates than the samples that are shipped. ****
**** This may be due to user customization or an update to the samples. ****
**** You should compare the following files to the samples in the same folder and update them. ****
**** Use the link at the top of the file to view the changelog. ****
┌────────────┬────────────┬────────────────────────────────────────────────────────────────────────┐
│  old date  │  new date  │ path                                                                   │
├────────────┼────────────┼────────────────────────────────────────────────────────────────────────┤
│ 2023-04-13 │ 2024-05-27 │ /config/nginx/nginx.conf                                               │
│ 2024-04-02 │ 2024-06-24 │ /config/nginx/site-confs/default.conf                                  │
└────────────┴────────────┴────────────────────────────────────────────────────────────────────────┘
[custom-init] No custom files found, skipping...
[ls.io-init] done.
```

**Comment by j0nnymoe** [comment] 2024-06-26 06:12
This isn't a bug, just an issue within your config of your reverse proxy or a networking issue.

Few things to check: 

- check you can acces it directly from your browser via proxied address
- check DNS
- make sure you're using split DNS rather than relying on NAT hairpin as I believe that causes nextcloud to trip up.

**Comment by gacpac** [comment] 2024-06-26 11:38
I cannot access from the outside via the proxies address if that is what
you mean.
DNS is good
I tried using split dns but it's hard to do when it's the same IP of the
unraid server so  it hits the wrong address.

**Comment by gacpac** [comment] 2024-07-02 23:44
Good afternoon,

The problem is not related to pinhold or Nat currently I can reach the documentserver.mydomain.com from the outside of my network no problem, yet trying to open a document still shows access denied.

I also deleted the docker from scratch and let it recreate if there's any issue should I look at the swag side of things?

**Comment by aptalca** [comment] 2024-07-03 00:14
Both nextcloud and onlyoffice need to be accessible at their respective domain names both inside and outside of your lan, because they try to reach each other via the domain names as well.

That's why you're instructed to set up split dns.

To clarify, the split dns would set the record for the domains to point to your reverse proxy (SWAG) internally and SWAG would proxy the necessary service. SWAG would need to be accessible at port 443 on the host IP.

These are the basic requirements for the simple setup.

Closing as it's not a bug. If you still need help, you can join our discord.

**Closed by aptalca** 2024-07-03 00:14 UTC

**Comment by gacpac** [comment] 2024-07-03 01:38
I'm speaking on the forum. Right now I don't care about split dns since I'm accessing from the outside where is reachable  and I have settings in my pfsense so when I hit externally it goes back reachable. That's how my nextcloud setup is working for years.

**Comment by aptalca** [comment] 2024-07-03 01:46
> That's how my nextcloud setup is working for years.

Like I said, this issue is not about Nextcloud itself

> Right now I don't care about split dns since I'm accessing from the outside

You might not care but onlyoffice does because as I said before `they try to reach each other via the domain names as well` and they are both inside of your lan, not outside

**Comment by gacpac** [comment] 2024-09-17 21:09
Good Afternoon, after long searches and different threads at the onlyoffice forum found a solution that is modifying the proxy config of the documentserver and adding 

add_header Content-Security-Policy "frame-ancestors 'self' https://nextcloud.mydomain.com";




reference 

https://forum.onlyoffice.com/t/nextcloud-onlyoffice-refused-to-connect/6563
