### ISSUE TITLE
[BUG] This version of Nextcloud is not compatible with > PHP 8.0. You are currently running 8.1.16.

### ISSUE THREAD

**Issue by PilaScat** [linuxserver/docker-nextcloud#286] opened 2023-02-23 15:32 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not starting
It tells on the web page:
This version of Nextcloud is not compatible with > PHP 8.0.
You are currently running 8.1.16.

### Expected Behavior

Start

### Steps To Reproduce

Update to latest

### Environment

```markdown
- OS: UNRAID
- How docker service was installed: UNRAID Apps
```

### CPU architecture

x86-64

### Docker creation

```bash
From the template of UNRAID Apps
```

### Container logs

```bash
nothing useful
```

**Comment by thespad** [comment] 2023-02-23 15:40
Duplicate of https://github.com/linuxserver/docker-nextcloud/issues/285

**Closed by thespad** 2023-02-23 15:40 UTC
